name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-in-local-repo:
    uses: renji2023/test_demo/.github/workflows/reusable_workflow2.yml@master





